"""
End-to-end tests for Django-aware mrt fix generated code.

Verifies that the backup/restore code pattern generated by mrt fix actually
executes correctly against a real SQLite database — not just that it parses.

Skipped automatically when Django is not installed.
"""

from __future__ import annotations

import textwrap
from pathlib import Path

import pytest

django = pytest.importorskip("django", reason="Django not installed")

INSTALLED_APPS = [
    "django.contrib.contenttypes",
    "django.contrib.auth",
    "tests.django_app",
    "tests.django_bad_app",
    "tests.django_fixer_app",
]

_BACKUP_LABEL = "0002_remove_phone__contact_phone"


@pytest.fixture(scope="module")
def fixer_runner(tmp_path_factory):
    from pytest_mrt.adapters.django_runner import DjangoMigrationRunner

    db_path = tmp_path_factory.mktemp("fixer_e2e") / "fixer.db"
    runner = DjangoMigrationRunner(
        db_url=f"sqlite:///{db_path}",
        installed_apps=INSTALLED_APPS,
    )
    yield runner
    runner.dispose()


def _clear_contacts() -> None:
    from django.db import connection

    with connection.cursor() as cur:
        cur.execute("DELETE FROM django_fixer_app_contact")


def _seed_contacts() -> list[dict]:
    from django.db import connection

    rows = [
        ("Alice", "555-0001"),
        ("Bob", "555-0002"),
        ("Carol", None),
    ]
    with connection.cursor() as cur:
        for name, phone in rows:
            cur.execute(
                "INSERT INTO django_fixer_app_contact (name, phone) VALUES (?, ?)",
                [name, phone],
            )
        cur.execute("SELECT id, name, phone FROM django_fixer_app_contact ORDER BY id")
        return [{"id": r[0], "name": r[1], "phone": r[2]} for r in cur.fetchall()]


def _read_contacts_with_phone() -> list[dict]:
    from django.db import connection

    with connection.cursor() as cur:
        cur.execute("SELECT id, name, phone FROM django_fixer_app_contact ORDER BY id")
        return [{"id": r[0], "name": r[1], "phone": r[2]} for r in cur.fetchall()]


def _read_backups() -> list[tuple]:
    from django.db import connection

    with connection.cursor() as cur:
        try:
            cur.execute(
                "SELECT object_id, payload FROM _mrt_backups WHERE migration_label = ?",
                [_BACKUP_LABEL],
            )
            return cur.fetchall()
        except Exception:
            return []


# ─────────────────────────────────────────────────────────────
# Codec round-trip (no Django needed)
# ─────────────────────────────────────────────────────────────


def _make_codec():
    """Return (enc, dec) from the reference migration module."""
    import importlib.util

    spec = importlib.util.spec_from_file_location(
        "_mrt_ref_migration",
        Path(__file__).parent / "django_fixer_app" / "migrations" / "0002_remove_phone.py",
    )
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.__mrt_enc, mod.__mrt_dec


def test_codec_roundtrip_common_types():
    """The inline codec handles all common Python types without loss."""
    enc, dec = _make_codec()

    from datetime import date, datetime, time
    from decimal import Decimal
    from uuid import UUID

    cases = [
        None,
        True,
        False,
        0,
        42,
        -7,
        3.14,
        Decimal("1.23456789"),
        datetime(2024, 6, 15, 12, 30, 45),
        date(2024, 6, 15),
        time(12, 30, 45),
        UUID("12345678-1234-5678-1234-567812345678"),
        b"\x00\xff\xab",
        "plain string",
        "D:already_tagged",
    ]

    for val in cases:
        assert dec(enc(val)) == val, f"round-trip failed for {val!r}"


# ─────────────────────────────────────────────────────────────
# Backup/restore execution against real SQLite
# ─────────────────────────────────────────────────────────────


def test_backup_writes_to_mrt_backups(fixer_runner):
    """Running migration 0002 forward writes contact phone data to _mrt_backups."""
    fixer_runner.upgrade("django_fixer_app", "0001_initial")
    _clear_contacts()
    seeded = _seed_contacts()

    fixer_runner.upgrade("django_fixer_app", "0002_remove_phone")

    backups = _read_backups()
    assert len(backups) == len(seeded), f"expected {len(seeded)} backup rows, got {len(backups)}"


def test_restore_recovers_phone_data(fixer_runner):
    """Rolling back migration 0002 restores phone data from _mrt_backups."""
    # Start clean at 0001
    fixer_runner.downgrade("django_fixer_app", "0002_remove_phone")
    _clear_contacts()
    seeded = _seed_contacts()
    phone_map = {r["id"]: r["phone"] for r in seeded}

    # Forward: backup runs, phone column removed
    fixer_runner.upgrade("django_fixer_app", "0002_remove_phone")
    # Backward: restore runs, phone column added back
    fixer_runner.downgrade("django_fixer_app", "0002_remove_phone")

    after = _read_contacts_with_phone()
    for row in after:
        assert row["phone"] == phone_map[row["id"]], (
            f"phone not restored for id={row['id']}: "
            f"expected {phone_map[row['id']]!r}, got {row['phone']!r}"
        )


def test_null_phone_survives_roundtrip(fixer_runner):
    """NULL phone values are backed up and restored as NULL."""
    fixer_runner.downgrade("django_fixer_app", "0002_remove_phone")
    _clear_contacts()
    seeded = _seed_contacts()

    fixer_runner.upgrade("django_fixer_app", "0002_remove_phone")
    fixer_runner.downgrade("django_fixer_app", "0002_remove_phone")

    after = _read_contacts_with_phone()
    null_before = {r["id"] for r in seeded if r["phone"] is None}
    null_after = {r["id"] for r in after if r["phone"] is None}
    assert null_before == null_after, (
        f"NULL phone IDs changed: before={null_before}, after={null_after}"
    )


def test_backup_rows_deleted_after_restore(fixer_runner):
    """After rollback, _mrt_backups rows for this migration are deleted."""
    fixer_runner.downgrade("django_fixer_app", "0002_remove_phone")
    _clear_contacts()
    _seed_contacts()

    fixer_runner.upgrade("django_fixer_app", "0002_remove_phone")
    fixer_runner.downgrade("django_fixer_app", "0002_remove_phone")

    remaining = _read_backups()
    assert remaining == [], f"backup rows should be cleaned up after restore, found {remaining}"


# ─────────────────────────────────────────────────────────────
# mrt fix generates the same pattern as the reference migration
# ─────────────────────────────────────────────────────────────


def test_generated_code_matches_reference_pattern(tmp_path):
    """mrt fix produces backup/restore code with the same structure as the reference."""
    from pytest_mrt.adapters.django_fixer import apply_django_fix, generate_django_fix

    migration_src = textwrap.dedent("""\
        from django.db import migrations, models


        class Migration(migrations.Migration):
            dependencies = [("django_fixer_app", "0001_initial")]

            operations = [
                migrations.RemoveField(model_name="contact", name="phone"),
            ]
    """)
    migrations_dir = tmp_path / "django_fixer_app" / "migrations"
    migrations_dir.mkdir(parents=True)
    p = migrations_dir / "0002_remove_phone.py"
    p.write_text(migration_src)

    fix = generate_django_fix(str(p))
    assert fix is not None
    apply_django_fix(str(p), fix)
    patched = p.read_text()

    assert "_backup_contact_phone" in patched
    assert "_restore_contact_phone" in patched
    assert "_mrt_backups" in patched
    assert "pk__gt" in patched
    assert "__mrt_enc" in patched
    assert "__mrt_dec" in patched
    assert "migrations.RunPython(" in patched
    assert patched.index("migrations.RunPython(") < patched.index("migrations.RemoveField(")
