"""
Django migration fix generator.

Generates fully-functional backup/restore code for Django migration operations
that would otherwise lose data on rollback.

  Structural fixes (no data loss risk):
    RunSQL without reverse_sql   -> adds reverse_sql=migrations.RunSQL.noop
    RunPython without reverse_code -> adds reverse_code=migrations.RunPython.noop

  Data-loss fixes (RemoveField, DeleteModel):
    Injects a RunPython(backup, restore) BEFORE the destructive operation.
    The backup/restore functions use a single shared _mrt_backups table in the
    same database.  Generated code is self-contained — no runtime pytest-mrt
    dependency.

Known limitations (documented in generated code comments):
  - Custom field types fall back to str() and may not restore correctly.
  - Large tables: keyset pagination is used but with atomic=False there is no
    snapshot isolation — rows inserted between chunks may be missed.
  - After a stable deployment, run `mrt clean-backups --db URL` to remove
    accumulated backup data from _mrt_backups.
  - squashmigrations: Django's squash tool does not understand the generated
    RunPython scaffolding and may remove or corrupt it.  Review squashed
    migrations manually.
"""

from __future__ import annotations

import ast
import re
from dataclasses import dataclass
from pathlib import Path

# ─────────────────────────────────────────────────────────────
# Codec block injected once per migration that has data-loss patches.
# Included inline so the migration has no runtime pytest-mrt dependency.
# ─────────────────────────────────────────────────────────────

_MRT_CODEC_BLOCK = """\
# ── mrt backup codec ─────────────────────────────────────────────────────────
# Generated by `mrt fix`.  Included inline — no runtime pytest-mrt dependency.
#
# Handled types: None, bool, int, float, str, Decimal, datetime (tz-aware and
# naive), date, time, UUID, bytes/memoryview, dict, list.
#
# KNOWN LIMITATIONS:
#   - Custom field types (e.g. MoneyField, ColorField) fall back to str() and
#     may not restore correctly.  Inspect __mrt_enc output before applying.
#   - Timezone-aware datetimes are stored as UTC POSIX timestamps; sub-second
#     precision is preserved but the original tzinfo is not.
#   - Binary fields are base64-encoded; very large values slow down the backup.
#   - Strings that begin with "D:", "d:", "DT:", "t:", "U:", "B:", or "S:" are
#     automatically escaped and will round-trip correctly.
_MRT_TABLE = "_mrt_backups"
_MRT_CHUNK = 1000


def __mrt_enc(v):
    if v is None or isinstance(v, (bool, int, float)):
        return v
    if isinstance(v, dict):
        return {k: __mrt_enc(w) for k, w in v.items()}
    if isinstance(v, list):
        return [__mrt_enc(w) for w in v]
    if isinstance(v, str):
        # escape strings whose prefix would collide with our type tags
        return ("S:" + v) if (v[:2] in ("D:", "d:", "t:", "U:", "B:", "S:") or v[:3] == "DT:") else v
    try:
        from decimal import Decimal
        if isinstance(v, Decimal):
            return "D:" + str(v)
    except ImportError:
        pass
    try:
        from datetime import datetime, date, time
        if isinstance(v, datetime):
            # store tz-aware as UTC POSIX timestamp to avoid Python 3.10
            # fromisoformat limitation with offset-aware strings
            return ("DTs:" + str(v.timestamp())) if v.tzinfo else ("DT:" + v.isoformat())
        if isinstance(v, date):
            return "d:" + v.isoformat()
        if isinstance(v, time):
            return "t:" + v.isoformat()
    except ImportError:
        pass
    try:
        import uuid
        if isinstance(v, uuid.UUID):
            return "U:" + str(v)
    except ImportError:
        pass
    if isinstance(v, (bytes, memoryview)):
        import base64
        return "B:" + base64.b64encode(bytes(v)).decode()
    return str(v)  # fallback: unknown type stored as str; may not restore


def __mrt_dec(v):
    if not isinstance(v, str):
        if isinstance(v, dict):
            return {k: __mrt_dec(w) for k, w in v.items()}
        if isinstance(v, list):
            return [__mrt_dec(w) for w in v]
        return v
    p, _, r = v.partition(":")
    if p == "S":
        return r
    if p == "D":
        from decimal import Decimal
        return Decimal(r)
    if p == "DTs":
        from datetime import datetime, timezone
        return datetime.fromtimestamp(float(r), tz=timezone.utc)
    if p == "DT":
        from datetime import datetime
        return datetime.fromisoformat(r)
    if p == "d":
        from datetime import date
        return date.fromisoformat(r)
    if p == "t":
        from datetime import time
        return time.fromisoformat(r)
    if p == "U":
        import uuid
        return uuid.UUID(r)
    if p == "B":
        import base64
        return base64.b64decode(r)
    return v
# ─────────────────────────────────────────────────────────────────────────────
"""

_MRT_TABLE = "_mrt_backups"


# ─────────────────────────────────────────────────────────────
# Data classes
# ─────────────────────────────────────────────────────────────


@dataclass
class DjangoOpPatch:
    line: int
    op_name: str
    issue: str
    original_snippet: str
    patched_snippet: str
    confidence: str
    prepend_to_class: str = ""  # label constant + backup/restore functions


@dataclass
class DjangoFixSuggestion:
    file: str
    migration_name: str
    patches: list[DjangoOpPatch]
    patched_source: str
    confidence: str
    warning: str | None = None
    # Operations detected by mrt check but not auto-fixable (e.g. AddField NOT NULL,
    # AlterField). Non-empty means the migration has issues mrt fix cannot resolve.
    unsupported_ops: list[str] | None = None

    @property
    def issue(self) -> str:
        if len(self.patches) == 1:
            return self.patches[0].issue
        names = ", ".join(p.op_name for p in self.patches)
        return f"{len(self.patches)} operations need fix: {names}"


# ─────────────────────────────────────────────────────────────
# AST helpers
# ─────────────────────────────────────────────────────────────


def _node_source(source: str, node: ast.AST) -> str:
    lines = source.splitlines()
    if node.lineno == node.end_lineno:  # type: ignore[attr-defined]
        return lines[node.lineno - 1][node.col_offset : node.end_col_offset]  # type: ignore[attr-defined]
    chunk = lines[node.lineno - 1][node.col_offset :]  # type: ignore[attr-defined]
    for ln in range(node.lineno, node.end_lineno - 1):  # type: ignore[attr-defined]
        chunk += "\n" + lines[ln]
    chunk += "\n" + lines[node.end_lineno - 1][: node.end_col_offset]  # type: ignore[attr-defined]
    return chunk


def _op_name(op: ast.expr) -> str:
    if isinstance(op, ast.Call):
        f = op.func
        if isinstance(f, ast.Attribute):
            return f.attr
        if isinstance(f, ast.Name):
            return f.id
    return ""


def _has_kwarg(op: ast.Call, name: str) -> bool:
    return any(kw.arg == name for kw in op.keywords)


def _add_field_is_problematic(op: ast.Call) -> bool:
    """Return True if AddField is NOT NULL with no default (MRT411 condition)."""
    for kw in op.keywords:
        if kw.arg == "field" and isinstance(kw.value, ast.Call):
            field_call = kw.value
            # null=True means it's safe
            for fkw in field_call.keywords:
                if fkw.arg == "null":
                    if isinstance(fkw.value, ast.Constant) and fkw.value.value is True:
                        return False
            # has default= or server_default= -> safe
            field_kwarg_names = {fkw.arg for fkw in field_call.keywords}
            if "default" in field_kwarg_names or "server_default" in field_kwarg_names:
                return False
            # No null=True and no default -> problematic
            return True
    return False


def _has_positional_arg(op: ast.Call, index: int) -> bool:
    return len(op.args) > index


def _kwarg_str(op: ast.Call, name: str) -> str | None:
    for kw in op.keywords:
        if kw.arg == name and isinstance(kw.value, ast.Constant):
            return str(kw.value.value)
    return None


def _slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")


# ─────────────────────────────────────────────────────────────
# Structural patches (RunSQL, RunPython)
# ─────────────────────────────────────────────────────────────


def _insert_kwarg(original: str, kwarg: str) -> str:
    assert original.endswith(")")
    open_paren = original.index("(")
    sep = ", " if original[open_paren + 1 : -1].strip() else ""
    return original[:-1] + sep + kwarg + ")"


def _patch_run_sql(source: str, op: ast.Call) -> DjangoOpPatch | None:
    if _has_kwarg(op, "reverse_sql") or _has_positional_arg(op, 1):
        return None
    original = _node_source(source, op)
    return DjangoOpPatch(
        line=op.lineno,
        op_name="RunSQL",
        issue=f"RunSQL at line {op.lineno} has no reverse_sql — cannot be rolled back",
        original_snippet=original,
        patched_snippet=_insert_kwarg(original, "reverse_sql=migrations.RunSQL.noop"),
        confidence="high",
    )


def _patch_run_python(source: str, op: ast.Call) -> DjangoOpPatch | None:
    if _has_kwarg(op, "reverse_code") or _has_positional_arg(op, 1):
        return None
    original = _node_source(source, op)
    return DjangoOpPatch(
        line=op.lineno,
        op_name="RunPython",
        issue=f"RunPython at line {op.lineno} has no reverse_code — data transformation cannot be undone",
        original_snippet=original,
        patched_snippet=_insert_kwarg(original, "reverse_code=migrations.RunPython.noop"),
        confidence="medium",
    )


# ─────────────────────────────────────────────────────────────
# Data-loss patches (RemoveField, DeleteModel)
# ─────────────────────────────────────────────────────────────


def _build_run_python_insertion(
    original: str, op: ast.Call, backup_fn: str, restore_fn: str
) -> str:
    indent = " " * op.col_offset
    inner = " " * (op.col_offset + 4)
    return (
        f"migrations.RunPython(\n"
        f"{inner}{backup_fn},\n"
        f"{inner}{restore_fn},\n"
        f"{indent}),\n"
        f"{indent}{original}"
    )


def _patch_remove_field(
    source: str, op: ast.Call, app_label: str, migration_stem: str
) -> DjangoOpPatch | None:
    model = _kwarg_str(op, "model_name") or "model"
    field_name = _kwarg_str(op, "name") or "field"
    suffix = f"{_slug(model)}_{_slug(field_name)}"
    label = f"{migration_stem}__{_slug(model)}_{_slug(field_name)}"
    backup_fn = f"_backup_{suffix}"
    restore_fn = f"_restore_{suffix}"
    model_cap = model.capitalize()

    original = _node_source(source, op)

    prepend = (
        f'_MRT_LABEL_{suffix} = "{label}"\n'
        f"\n"
        f"\n"
        f"def {backup_fn}(apps, schema_editor):\n"
        f"    import json\n"
        f"    from django.db import connection\n"
        f"    {model_cap} = apps.get_model('{app_label}', '{model_cap}')\n"
        f"    with connection.cursor() as cur:\n"
        f"        cur.execute(\n"
        f'            "CREATE TABLE IF NOT EXISTS " + _MRT_TABLE + " "\n'
        f'            "(migration_label TEXT NOT NULL, object_id TEXT NOT NULL, payload TEXT)"\n'
        f"        )\n"
        f"        cur.execute(\n"
        f'            "DELETE FROM " + _MRT_TABLE + " WHERE migration_label = %s",\n'
        f"            [_MRT_LABEL_{suffix}],\n"
        f"        )\n"
        f"    last_pk = None\n"
        f"    while True:\n"
        f"        qs = {model_cap}.objects.order_by('pk')\n"
        f"        if last_pk is not None:\n"
        f"            qs = qs.filter(pk__gt=last_pk)\n"
        f"        batch = list(qs.values_list('pk', '{field_name}')[:_MRT_CHUNK])\n"
        f"        if not batch:\n"
        f"            break\n"
        f"        with connection.cursor() as cur:\n"
        f"            for pk, val in batch:\n"
        f"                cur.execute(\n"
        f'                    "INSERT INTO " + _MRT_TABLE + " VALUES (%s, %s, %s)",\n'
        f"                    [_MRT_LABEL_{suffix}, json.dumps(__mrt_enc(pk)), json.dumps(__mrt_enc(val))],\n"
        f"                )\n"
        f"        last_pk = batch[-1][0]\n"
        f"\n"
        f"\n"
        f"def {restore_fn}(apps, schema_editor):\n"
        f"    import json\n"
        f"    from django.db import connection\n"
        f"    {model_cap} = apps.get_model('{app_label}', '{model_cap}')\n"
        f"    with connection.cursor() as cur:\n"
        f"        cur.execute(\n"
        f'            "SELECT object_id, payload FROM " + _MRT_TABLE + " WHERE migration_label = %s",\n'
        f"            [_MRT_LABEL_{suffix}],\n"
        f"        )\n"
        f"        rows = cur.fetchall()\n"
        f"    for pk_raw, val_raw in rows:\n"
        f"        pk = __mrt_dec(json.loads(pk_raw))\n"
        f"        val = __mrt_dec(json.loads(val_raw))\n"
        f"        {model_cap}.objects.filter(pk=pk).update({field_name}=val)\n"
        f"    with connection.cursor() as cur:\n"
        f"        cur.execute(\n"
        f'            "DELETE FROM " + _MRT_TABLE + " WHERE migration_label = %s",\n'
        f"            [_MRT_LABEL_{suffix}],\n"
        f"        )\n"
    )

    return DjangoOpPatch(
        line=op.lineno,
        op_name="RemoveField",
        issue=f"RemoveField('{model}', '{field_name}') at line {op.lineno} — field data permanently lost on rollback",
        original_snippet=original,
        patched_snippet=_build_run_python_insertion(original, op, backup_fn, restore_fn),
        confidence="medium",
        prepend_to_class=prepend,
    )


def _patch_delete_model(
    source: str, op: ast.Call, app_label: str, migration_stem: str
) -> DjangoOpPatch | None:
    model = _kwarg_str(op, "name") or "Model"
    suffix = f"{_slug(model)}_rows"
    label = f"{migration_stem}__{_slug(model)}_rows"
    backup_fn = f"_backup_{suffix}"
    restore_fn = f"_restore_{suffix}"

    original = _node_source(source, op)

    prepend = (
        f'_MRT_LABEL_{suffix} = "{label}"\n'
        f"\n"
        f"\n"
        f"def {backup_fn}(apps, schema_editor):\n"
        f"    import json\n"
        f"    from django.db import connection\n"
        f"    {model} = apps.get_model('{app_label}', '{model}')\n"
        f"    pk_field = {model}._meta.pk\n"
        f"    field_names = [fld.attname for fld in {model}._meta.concrete_fields]\n"
        f"    with connection.cursor() as cur:\n"
        f"        cur.execute(\n"
        f'            "CREATE TABLE IF NOT EXISTS " + _MRT_TABLE + " "\n'
        f'            "(migration_label TEXT NOT NULL, object_id TEXT NOT NULL, payload TEXT)"\n'
        f"        )\n"
        f"        cur.execute(\n"
        f'            "DELETE FROM " + _MRT_TABLE + " WHERE migration_label = %s",\n'
        f"            [_MRT_LABEL_{suffix}],\n"
        f"        )\n"
        f"    last_pk = None\n"
        f"    while True:\n"
        f"        qs = {model}.objects.order_by('pk')\n"
        f"        if last_pk is not None:\n"
        f"            qs = qs.filter(pk__gt=last_pk)\n"
        f"        batch = list(qs.values(*field_names)[:_MRT_CHUNK])\n"
        f"        if not batch:\n"
        f"            break\n"
        f"        with connection.cursor() as cur:\n"
        f"            for row in batch:\n"
        f"                pk_val = row[pk_field.attname]\n"
        f"                payload = {{k: __mrt_enc(v) for k, v in row.items()}}\n"
        f"                cur.execute(\n"
        f'                    "INSERT INTO " + _MRT_TABLE + " VALUES (%s, %s, %s)",\n'
        f"                    [_MRT_LABEL_{suffix}, json.dumps(__mrt_enc(pk_val)), json.dumps(payload)],\n"
        f"                )\n"
        f"        last_pk = batch[-1][pk_field.attname]\n"
        f"\n"
        f"\n"
        f"def {restore_fn}(apps, schema_editor):\n"
        f"    # Uses raw SQL INSERT + disable_constraint_checking to handle FK ordering.\n"
        f"    # If restore fails with IntegrityError, check that referenced models are\n"
        f"    # restored in the correct migration order.\n"
        f"    import json\n"
        f"    from django.db import connection\n"
        f"    {model} = apps.get_model('{app_label}', '{model}')\n"
        f"    fields = {model}._meta.concrete_fields\n"
        f"    col_names = ', '.join(f.column for f in fields)\n"
        f"    placeholders = ', '.join(['%s'] * len(fields))\n"
        f"    with connection.cursor() as cur:\n"
        f"        cur.execute(\n"
        f'            "SELECT payload FROM " + _MRT_TABLE + " WHERE migration_label = %s",\n'
        f"            [_MRT_LABEL_{suffix}],\n"
        f"        )\n"
        f"        rows = [json.loads(r[0]) for r in cur.fetchall()]\n"
        f"    schema_editor.connection.disable_constraint_checking()\n"
        f"    try:\n"
        f"        with connection.cursor() as cur:\n"
        f"            for payload in rows:\n"
        f"                decoded = {{k: __mrt_dec(v) for k, v in payload.items()}}\n"
        f"                values = [decoded.get(f.attname) for f in fields]\n"
        f"                cur.execute(\n"
        f'                    f"INSERT INTO {{{model}._meta.db_table}} ({{col_names}}) VALUES ({{placeholders}})",\n'
        f"                    values,\n"
        f"                )\n"
        f"    finally:\n"
        f"        schema_editor.connection.enable_constraint_checking()\n"
        f"    with connection.cursor() as cur:\n"
        f"        cur.execute(\n"
        f'            "DELETE FROM " + _MRT_TABLE + " WHERE migration_label = %s",\n'
        f"            [_MRT_LABEL_{suffix}],\n"
        f"        )\n"
    )

    return DjangoOpPatch(
        line=op.lineno,
        op_name="DeleteModel",
        issue=f"DeleteModel('{model}') at line {op.lineno} — all rows permanently lost on rollback",
        original_snippet=original,
        patched_snippet=_build_run_python_insertion(original, op, backup_fn, restore_fn),
        confidence="medium",
        prepend_to_class=prepend,
    )


# ─────────────────────────────────────────────────────────────
# Source patcher
# ─────────────────────────────────────────────────────────────


def _apply_patches_to_source(source: str, patches: list[DjangoOpPatch]) -> str:
    has_data_loss = any(p.prepend_to_class for p in patches)

    # 1. Inject codec block + per-patch stubs before `class Migration`
    prepends: list[str] = []
    if has_data_loss:
        prepends.append(_MRT_CODEC_BLOCK)
    for p in patches:
        if p.prepend_to_class:
            prepends.append(p.prepend_to_class)

    if prepends:
        block = "\n\n".join(prepends) + "\n\n"
        source = re.sub(
            r"^class Migration",
            block + "class Migration",
            source,
            count=1,
            flags=re.MULTILINE,
        )

    # 2. Apply in-place op replacements in reverse line order
    for p in sorted(patches, key=lambda x: x.line, reverse=True):
        source = source.replace(p.original_snippet, p.patched_snippet, 1)

    return source


# ─────────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────────


def is_django_migration(path: Path) -> bool:
    try:
        src = path.read_text()
        return "class Migration" in src and "django.db" in src
    except Exception:
        return False


def generate_django_fix(migration_path: str) -> DjangoFixSuggestion | None:
    """
    Analyze a Django migration file and return a fix suggestion.

    Structural fixes (high/medium confidence, no data movement):
      RunSQL without reverse_sql   -> reverse_sql=migrations.RunSQL.noop
      RunPython without reverse_code -> reverse_code=migrations.RunPython.noop

    Data-loss fixes (medium confidence, fully functional backup/restore):
      RemoveField -> RunPython(backup, restore) injected before the op
      DeleteModel -> RunPython(backup, restore) injected before the op

    Generated code stores backup data in a shared _mrt_backups table using
    keyset-paginated chunked writes.  See module docstring for limitations.

    Returns None if no fix is needed.
    """
    path = Path(migration_path)
    source = path.read_text()

    try:
        tree = ast.parse(source)
    except SyntaxError as e:
        raise ValueError(f"Cannot parse {path.name}: {e}") from e

    migration_class: ast.ClassDef | None = None
    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef) and node.name == "Migration":
            migration_class = node
            break
    if migration_class is None:
        return None

    ops_list: list[ast.expr] = []
    for item in migration_class.body:
        if isinstance(item, ast.Assign):
            for target in item.targets:
                if isinstance(target, ast.Name) and target.id == "operations":
                    if isinstance(item.value, ast.List):
                        ops_list = item.value.elts

    app_label = path.parent.parent.name
    migration_name = f"{app_label}.{path.stem}"
    migration_stem = path.stem

    # Operations that mrt check may flag but mrt fix cannot auto-resolve.
    # Only truly irreversible variants are listed — e.g. AddField(null=True) is
    # fine, but AddField NOT NULL without a default is flagged by mrt check and
    # cannot be auto-fixed. We detect these by name only (the detector handles
    # the nuance); here we just surface them to the user.
    _UNSUPPORTED_OPS = {"AlterField", "RenameField", "RenameModel"}

    patches: list[DjangoOpPatch] = []
    unsupported: list[str] = []

    for op in ops_list:
        if not isinstance(op, ast.Call):
            continue
        name = _op_name(op)

        patch: DjangoOpPatch | None = None
        if name == "RunSQL":
            patch = _patch_run_sql(source, op)
        elif name == "RunPython":
            patch = _patch_run_python(source, op)
        elif name == "RemoveField":
            patch = _patch_remove_field(source, op, app_label, migration_stem)
        elif name == "DeleteModel":
            patch = _patch_delete_model(source, op, app_label, migration_stem)
        elif name == "AddField":
            # Only flag AddField that is NOT NULL with no default — same condition
            # that mrt check (MRT411) flags. null=True or a default= means it's safe.
            if _add_field_is_problematic(op):
                unsupported.append("AddField NOT NULL without default")
        elif name in _UNSUPPORTED_OPS:
            unsupported.append(name)

        if patch is not None:
            patches.append(patch)

    if not patches:
        # Return a suggestion with no patches but unsupported ops listed,
        # so the caller can show a meaningful message instead of "no fix needed".
        if unsupported:
            return DjangoFixSuggestion(
                file=path.name,
                migration_name=migration_name,
                patches=[],
                patched_source=source,
                confidence="none",
                unsupported_ops=unsupported,
            )
        return None

    patched_source = _apply_patches_to_source(source, patches)

    confidences = {p.confidence for p in patches}
    overall = "low" if "low" in confidences else ("medium" if "medium" in confidences else "high")

    warnings: list[str] = []
    if any(p.op_name == "RunPython" for p in patches):
        warnings.append(
            "RunPython reverse set to migrations.RunPython.noop — does NOT undo "
            "data changes. Replace noop with a real reverse function."
        )
    if any(p.op_name in ("RemoveField", "DeleteModel") for p in patches):
        warnings.append(
            "Backup/restore code injected. Run `mrt clean-backups --db URL` "
            "after confirming stable deployment to remove backup data."
        )

    return DjangoFixSuggestion(
        file=path.name,
        migration_name=migration_name,
        patches=patches,
        patched_source=patched_source,
        confidence=overall,
        warning="\n\n".join(warnings) if warnings else None,
    )


def apply_django_fix(migration_path: str, fix: DjangoFixSuggestion) -> None:
    """Write the patched source to the migration file."""
    Path(migration_path).write_text(fix.patched_source)
